// GENERATED by tools/cloud-points.mjs — do not hand-edit.
//
// Landmark indices for the live overlay's point cloud, chosen by greedy
// farthest-point sampling over an averaged canonical face and mirrored into
// exact left/right pairs. Even spacing, symmetric, no boundary points.
//
// Averaged over 16 faces. Nearest-neighbour spacing, in face widths:
// min 0.0574, median 0.1006, max 0.1459.
//
// The list is FIXED so every frame draws the same anatomical points and the
// cloud deforms with the face. Reselecting per frame would shimmer.
export const CLOUD_POINTS: readonly number[] = [
  0, 4, 6, 7, 9, 18, 22, 52, 65, 69, 97, 104, 107, 108, 114, 116, 118, 135, 137, 139, 142, 146, 151, 165, 170, 175, 177, 180, 189, 194, 195, 202, 205, 208, 213, 216, 247, 253, 255, 295, 298, 299, 336, 337, 343, 347, 353, 364, 367, 371, 391, 392, 395, 401, 404, 414, 418, 422, 425, 428, 435, 436, 444, 447,
];
