import type { Sex } from "./types.ts";

// GENERATED by tools/normalize.mjs — do not hand-edit.
//
// Mean/SD of each aggregate z across the general-population reference set
// (people notable for their work, not their appearance). Applying these makes
// the population median score exactly 5.0 and one SD exactly 1.3 score
// points, so percentile claims are anchored to a real sample.
export const AGG_NORM: Record<Sex, Record<string, { mean: number; sd: number }>> = {
  male: {
    "pillar:Harmony": { mean: -0.3242, sd: 0.7502 },
    "pillar:Angularity": { mean: 0.1274, sd: 0.6007 },
    "pillar:Dimorphism": { mean: 0.0325, sd: 0.9531 },
    "pillar:Features": { mean: -0.208, sd: 0.9621 },
    "overall": { mean: 0.0756, sd: 0.8321 },
    "region:eyes": { mean: -0.1734, sd: 1.0603 },
    "region:midface": { mean: 0.0068, sd: 1.0215 },
    "region:jaw": { mean: 0.0981, sd: 0.6754 },
    "region:chin": { mean: -0.0563, sd: 1.0963 },
    "region:nose": { mean: -0.1906, sd: 0.8573 },
    "region:lips": { mean: -0.2291, sd: 0.8783 },
    "region:proportions": { mean: -0.3725, sd: 0.889 },
    "region:symmetry": { mean: -0.1317, sd: 0.9696 },
  },
  female: {
    "pillar:Harmony": { mean: -0.3364, sd: 0.6918 },
    "pillar:Angularity": { mean: -0.5047, sd: 0.5941 },
    "pillar:Dimorphism": { mean: -0.0951, sd: 0.8886 },
    "pillar:Features": { mean: -0.2553, sd: 1.4549 },
    "overall": { mean: -0.2004, sd: 0.7411 },
    "region:eyes": { mean: -0.5935, sd: 1.0135 },
    "region:midface": { mean: -0.0233, sd: 1.0743 },
    "region:jaw": { mean: -0.3936, sd: 0.4993 },
    "region:chin": { mean: 0.2596, sd: 0.9282 },
    "region:nose": { mean: -0.1053, sd: 0.8022 },
    "region:lips": { mean: -0.2956, sd: 1.1455 },
    "region:proportions": { mean: -0.3628, sd: 0.6184 },
    "region:symmetry": { mean: 0.0934, sd: 1.2723 },
  },
};
