import type { Sex } from "./types.ts";

// GENERATED by tools/normalize.mjs — do not hand-edit.
//
// Mean/SD of each aggregate z across the general-population reference set
// (people notable for their work, not their appearance). Applying these makes
// the population median score exactly 5.0 and one SD exactly 1.3 score
// points, so percentile claims are anchored to a real sample.
export const AGG_NORM: Record<Sex, Record<string, { mean: number; sd: number }>> = {
  male: {
    "pillar:Harmony": { mean: -0.2187, sd: 0.6885 },
    "pillar:Angularity": { mean: 0.2086, sd: 0.5983 },
    "pillar:Dimorphism": { mean: -0.0964, sd: 0.9973 },
    "pillar:Features": { mean: -0.2785, sd: 0.9565 },
    "overall": { mean: -0.0658, sd: 0.7633 },
    "region:eyes": { mean: -0.1733, sd: 1.0614 },
    "region:midface": { mean: -0.0382, sd: 0.9773 },
    "region:jaw": { mean: 0.1047, sd: 0.6651 },
    "region:chin": { mean: -0.0938, sd: 1.1463 },
    "region:nose": { mean: -0.231, sd: 0.8879 },
    "region:lips": { mean: -0.2343, sd: 0.8808 },
    "region:proportions": { mean: -0.101, sd: 0.8264 },
    "region:symmetry": { mean: -0.0385, sd: 0.9953 },
  },
  female: {
    "pillar:Harmony": { mean: 0.0806, sd: 0.7977 },
    "pillar:Angularity": { mean: 0.0203, sd: 0.5317 },
    "pillar:Dimorphism": { mean: -0.2174, sd: 0.5158 },
    "pillar:Features": { mean: -0.2459, sd: 1.134 },
    "overall": { mean: -0.1321, sd: 0.7906 },
    "region:eyes": { mean: -0.4746, sd: 0.732 },
    "region:midface": { mean: -0.7782, sd: 0.762 },
    "region:jaw": { mean: 0.4693, sd: 0.6506 },
    "region:chin": { mean: 0.3119, sd: 1.2481 },
    "region:nose": { mean: 0.3609, sd: 1.2528 },
    "region:lips": { mean: -0.0198, sd: 0.9192 },
    "region:proportions": { mean: 0.1568, sd: 0.6525 },
    "region:symmetry": { mean: -0.0638, sd: 1.1901 },
  },
};
