import type { Sex } from "./types.ts";

// GENERATED by tools/normalize.mjs — do not hand-edit.
//
// Mean/SD of each aggregate z across the general-population reference set
// (people notable for their work, not their appearance). Applying these makes
// the population median score exactly 5.0 and one SD exactly 1.3 score
// points, so percentile claims are anchored to a real sample.
export const AGG_NORM: Record<Sex, Record<string, { mean: number; sd: number }>> = {
  male: {
    "pillar:Harmony": { mean: -0.3548, sd: 0.6397 },
    "pillar:Angularity": { mean: -0.0746, sd: 0.7197 },
    "pillar:Dimorphism": { mean: 0.0621, sd: 0.7366 },
    "pillar:Features": { mean: -0.3658, sd: 0.8938 },
    "overall": { mean: 0.0115, sd: 1.1431 },
    "region:eyes": { mean: -0.2736, sd: 0.8322 },
    "region:midface": { mean: -0.1175, sd: 1.3131 },
    "region:jaw": { mean: -0.2552, sd: 0.7558 },
    "region:chin": { mean: 0.1582, sd: 1.0484 },
    "region:nose": { mean: -0.184, sd: 0.807 },
    "region:lips": { mean: -0.3333, sd: 0.8931 },
    "region:proportions": { mean: -0.3834, sd: 0.8859 },
    "region:symmetry": { mean: 0.1293, sd: 0.9946 },
  },
  female: {
    "pillar:Harmony": { mean: -0.2694, sd: 0.5069 },
    "pillar:Angularity": { mean: -0.4993, sd: 0.4933 },
    "pillar:Dimorphism": { mean: -0.2606, sd: 0.8074 },
    "pillar:Features": { mean: -0.1506, sd: 1.2955 },
    "overall": { mean: 0.0256, sd: 1.252 },
    "region:eyes": { mean: -0.2943, sd: 0.9361 },
    "region:midface": { mean: -0.0534, sd: 1.2541 },
    "region:jaw": { mean: -0.4678, sd: 0.3734 },
    "region:chin": { mean: -0.0432, sd: 0.9675 },
    "region:nose": { mean: -0.3712, sd: 0.8315 },
    "region:lips": { mean: -0.2595, sd: 0.5797 },
    "region:proportions": { mean: -0.3634, sd: 0.6187 },
    "region:symmetry": { mean: -0.2528, sd: 0.7504 },
  },
};
