// Generated from verified Commons metadata by scripts/sync-celebrity-portraits.ts.
// Portraits identify the person, not necessarily the photograph that was measured.
import type { CelebrityPortrait } from "./portraitLicense.js";
export type { CelebrityPortrait } from "./portraitLicense.js";

const PORTRAITS: Readonly<Record<string, CelebrityPortrait>> = {
  "Jordan Barrett": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Jordan-barrett-mbfw-march-2022-fashion-week-berlin.jpg/330px-Jordan-barrett-mbfw-march-2022-fashion-week-berlin.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Jordan-barrett-mbfw-march-2022-fashion-week-berlin.jpg",
    "title": "Jordan-barrett-mbfw-march-2022-fashion-week-berlin",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jordan-barrett-mbfw-march-2022-fashion-week-berlin.jpg",
    "author": "Nordfriisk",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "David Gandy": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/David_Gandy_1.jpg/330px-David_Gandy_1.jpg",
    "width": 322,
    "height": 440,
    "fileTitle": "File:David Gandy 1.jpg",
    "title": "David Gandy 1",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:David_Gandy_1.jpg",
    "author": "David Seow",
    "sourceCredit": "This image has been extracted from another file",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Sean O'Pry": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Sean_O%27Pry_2015.jpg/330px-Sean_O%27Pry_2015.jpg",
    "width": 330,
    "height": 409,
    "fileTitle": "File:Sean O'Pry 2015.jpg",
    "title": "Sean O'Pry 2015",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sean_O%27Pry_2015.jpg",
    "author": "Denielle",
    "sourceCredit": "Taylor Swift Concert 8-22-15 (228)",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Henry Cavill": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Henry_Cavill_%2848417913146%29_%28cropped%29.jpg/330px-Henry_Cavill_%2848417913146%29_%28cropped%29.jpg",
    "width": 330,
    "height": 431,
    "fileTitle": "File:Henry Cavill (48417913146) (cropped).jpg",
    "title": "Henry Cavill (48417913146) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Henry_Cavill_(48417913146)_(cropped).jpg",
    "author": "Gage Skidmore from Peoria, AZ, United States of America",
    "sourceCredit": "Freya Allan & Henry Cavill",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Christian Bale": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Christian_Bale-7837.jpg/330px-Christian_Bale-7837.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Christian Bale-7837.jpg",
    "title": "Christian Bale-7837",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Christian_Bale-7837.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Brad Pitt": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Brad_Pitt-69858.jpg/330px-Brad_Pitt-69858.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Brad Pitt-69858.jpg",
    "title": "Brad Pitt-69858",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brad_Pitt-69858.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Leonardo DiCaprio": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/LeoPTABFI191125-28_%28cropped%29.jpg/330px-LeoPTABFI191125-28_%28cropped%29.jpg",
    "width": 317,
    "height": 440,
    "fileTitle": "File:LeoPTABFI191125-28 (cropped).jpg",
    "title": "LeoPTABFI191125-28 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeoPTABFI191125-28_(cropped).jpg",
    "author": "Raph_PH",
    "sourceCredit": "https://www.flickr.com/photos/raph_ph/54940587709/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Tom Cruise": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg/330px-Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Tom Cruise at 53rd Saturn Awards 2026-01.jpg",
    "title": "Tom Cruise at 53rd Saturn Awards 2026-01",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Chris Hemsworth": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Chris_Hemsworth_-_Crime_101.jpg/330px-Chris_Hemsworth_-_Crime_101.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Chris Hemsworth - Crime 101.jpg",
    "title": "Chris Hemsworth - Crime 101",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chris_Hemsworth_-_Crime_101.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Ryan Gosling": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/62/GoslingBFI081223_%2822_of_30%29_%2853388157347%29_%28cropped%29.jpg/330px-GoslingBFI081223_%2822_of_30%29_%2853388157347%29_%28cropped%29.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:GoslingBFI081223 (22 of 30) (53388157347) (cropped).jpg",
    "title": "GoslingBFI081223 (22 of 30) (53388157347) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:GoslingBFI081223_(22_of_30)_(53388157347)_(cropped).jpg",
    "author": "Raph_PH",
    "sourceCredit": "GoslingBFI081223 (22 of 30)",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Michael B. Jordan": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Michael_B_Jordan_-_Sinners_%28cropped%29.jpg/330px-Michael_B_Jordan_-_Sinners_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Michael B Jordan - Sinners (cropped).jpg",
    "title": "Michael B Jordan - Sinners (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Michael_B_Jordan_-_Sinners_(cropped).jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Idris Elba": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Idris_Elba_A_House_of_Dynamite-21_%28cropped%29.jpg/330px-Idris_Elba_A_House_of_Dynamite-21_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Idris Elba A House of Dynamite-21 (cropped).jpg",
    "title": "Idris Elba A House of Dynamite-21 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Idris_Elba_A_House_of_Dynamite-21_(cropped).jpg",
    "author": "Bryan Berlin",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Zac Efron": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Zac_Efron_at_the_Baywatch_Red_Carpet_Premiere_Sydney_Australia.jpg/330px-Zac_Efron_at_the_Baywatch_Red_Carpet_Premiere_Sydney_Australia.jpg",
    "width": 294,
    "height": 440,
    "fileTitle": "File:Zac Efron at the Baywatch Red Carpet Premiere Sydney Australia.jpg",
    "title": "Zac Efron at the Baywatch Red Carpet Premiere Sydney Australia",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zac_Efron_at_the_Baywatch_Red_Carpet_Premiere_Sydney_Australia.jpg",
    "author": "Eva Rinaldi",
    "sourceCredit": "https://www.flickr.com/photos/evarinaldiphotography/34732955995/in/album-72157680824643334/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Timothée Chalamet": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Timoth%C3%A9e_Chalamet-63482_%28cropped%29.jpg/330px-Timoth%C3%A9e_Chalamet-63482_%28cropped%29.jpg",
    "width": 325,
    "height": 440,
    "fileTitle": "File:Timothée Chalamet-63482 (cropped).jpg",
    "title": "Timothée Chalamet-63482 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Timoth%C3%A9e_Chalamet-63482_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "Harald Krichel / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Robert Pattinson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Robert_Pattinson_at_Berlinale_2025.jpg/330px-Robert_Pattinson_at_Berlinale_2025.jpg",
    "width": 330,
    "height": 437,
    "fileTitle": "File:Robert Pattinson at Berlinale 2025.jpg",
    "title": "Robert Pattinson at Berlinale 2025",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Robert_Pattinson_at_Berlinale_2025.jpg",
    "author": "Elena Ternovaja",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jake Gyllenhaal": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/JakeGyllenhaal-byPhilipRomano.jpg/330px-JakeGyllenhaal-byPhilipRomano.jpg",
    "width": 330,
    "height": 422,
    "fileTitle": "File:JakeGyllenhaal-byPhilipRomano.jpg",
    "title": "JakeGyllenhaal-byPhilipRomano",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:JakeGyllenhaal-byPhilipRomano.jpg",
    "author": "PhilipRomanoPhoto",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Keanu Reeves": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg/330px-Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Keanu Reeves at TIFF 2025 02 (Cropped).jpg",
    "title": "Keanu Reeves at TIFF 2025 02 (Cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Keanu_Reeves_at_TIFF_2025_02_(Cropped).jpg",
    "author": "Gabriel Hutchinson",
    "sourceCredit": "Own work",
    "attribution": "Gabriel Hutchinson / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Johnny Depp": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Johnny_Depp_2020.jpg/330px-Johnny_Depp_2020.jpg",
    "width": 320,
    "height": 440,
    "fileTitle": "File:Johnny Depp 2020.jpg",
    "title": "Johnny Depp 2020",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Johnny_Depp_2020.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "George Clooney": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/George_Clooney_Jay_Kelly-19_%28cropped%29.jpg/330px-George_Clooney_Jay_Kelly-19_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:George Clooney Jay Kelly-19 (cropped).jpg",
    "title": "George Clooney Jay Kelly-19 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:George_Clooney_Jay_Kelly-19_(cropped).jpg",
    "author": "Bryan Berlin",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Cillian Murphy": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Cillian_Murphy_at_the_London_premier_of_Steve_in_September_2025_%28cropped%29.jpg/330px-Cillian_Murphy_at_the_London_premier_of_Steve_in_September_2025_%28cropped%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Cillian Murphy at the London premier of Steve in September 2025 (cropped).jpg",
    "title": "Cillian Murphy at the London premier of Steve in September 2025 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cillian_Murphy_at_the_London_premier_of_Steve_in_September_2025_(cropped).jpg",
    "author": "Netflix",
    "sourceCredit": "Provided by Netflix.",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Tom Hardy": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Tom_Hardy_%2841869508740%29.jpg/330px-Tom_Hardy_%2841869508740%29.jpg",
    "width": 330,
    "height": 220,
    "fileTitle": "File:Tom Hardy (41869508740).jpg",
    "title": "Tom Hardy (41869508740)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tom_Hardy_(41869508740).jpg",
    "author": "Gage Skidmore from Peoria, AZ, United States of America",
    "sourceCredit": "Tom Hardy",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jason Momoa": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Jason_Momoa_%2843055621224%29_%28cropped%29.jpg/330px-Jason_Momoa_%2843055621224%29_%28cropped%29.jpg",
    "width": 330,
    "height": 405,
    "fileTitle": "File:Jason Momoa (43055621224) (cropped).jpg",
    "title": "Jason Momoa (43055621224) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jason_Momoa_(43055621224)_(cropped).jpg",
    "author": "Gage Skidmore from Peoria, AZ, United States of America",
    "sourceCredit": "Jason Momoa",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Harry Styles": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/HarryStylesWembley170623_%2865_of_93%29_%2852982678051%29_%28cropped_2%29.jpg/330px-HarryStylesWembley170623_%2865_of_93%29_%2852982678051%29_%28cropped_2%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:HarryStylesWembley170623 (65 of 93) (52982678051) (cropped 2).jpg",
    "title": "HarryStylesWembley170623 (65 of 93) (52982678051) (cropped 2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HarryStylesWembley170623_(65_of_93)_(52982678051)_(cropped_2).jpg",
    "author": "Raph_PH",
    "sourceCredit": "HarryStylesWembley170623 (65 of 93)",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Zayn Malik": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/330px-Zayn_Wiki_%28cropped%29.jpg",
    "width": 329,
    "height": 440,
    "fileTitle": "File:Zayn Wiki (cropped).jpg",
    "title": "Zayn Wiki (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zayn_Wiki_(cropped).jpg",
    "author": "First Access Entertainment",
    "sourceCredit": "Majora received this from the author/copyright holder.",
    "attribution": "First Access Entertainment",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Cristiano Ronaldo": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg/330px-Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Cristiano Ronaldo Croatia v Portugal 2 July 2026-075 (cropped).jpg",
    "title": "Cristiano Ronaldo Croatia v Portugal 2 July 2026-075 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_(cropped).jpg",
    "author": "Bryan Berlin",
    "sourceCredit": "Own work",
    "attribution": "Bryan Berlin / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "David Beckham": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/David_Beckham_UNICEF_%28cropped2%29.jpg/330px-David_Beckham_UNICEF_%28cropped2%29.jpg",
    "width": 325,
    "height": 440,
    "fileTitle": "File:David Beckham UNICEF (cropped2).jpg",
    "title": "David Beckham UNICEF (cropped2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:David_Beckham_UNICEF_(cropped2).jpg",
    "author": "Soccer Aid for Unicef",
    "sourceCredit": "YouTube : https://www.youtube.com/watch?v=zkdEY911KsA&ab_channel=SoccerAidforUnicef – View/save archived versions on archive.org",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Lionel Messi": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg/330px-Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Leo Messi Argentina v Egypt 7 July 2026-1.jpg",
    "title": "Leo Messi Argentina v Egypt 7 July 2026-1",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg",
    "author": "Bryan Berlin",
    "sourceCredit": "Own work",
    "attribution": "Bryan Berlin / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Jeremy Allen White": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Jeremy_Allen_White_Springsteen-33_%28cropped%29.jpg/330px-Jeremy_Allen_White_Springsteen-33_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Jeremy Allen White Springsteen-33 (cropped).jpg",
    "title": "Jeremy Allen White Springsteen-33 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jeremy_Allen_White_Springsteen-33_(cropped).jpg",
    "author": "Bryan Berlin",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Pete Davidson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Pete_Davidson_portrait_%28cropped%29.png/330px-Pete_Davidson_portrait_%28cropped%29.png",
    "width": 330,
    "height": 428,
    "fileTitle": "File:Pete Davidson portrait (cropped).png",
    "title": "Pete Davidson portrait (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pete_Davidson_portrait_(cropped).png",
    "author": "LaVar James",
    "sourceCredit": "LaVar James",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Adam Driver": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Adam_Driver.jpg/330px-Adam_Driver.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Adam Driver.jpg",
    "title": "Adam Driver",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Adam_Driver.jpg",
    "author": "Colleen Sturtevant",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Barry Keoghan": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Barry_Keoghan_at_the_2024_Toronto_International_Film_Festival_%28cropped%29.jpg/330px-Barry_Keoghan_at_the_2024_Toronto_International_Film_Festival_%28cropped%29.jpg",
    "width": 330,
    "height": 416,
    "fileTitle": "File:Barry Keoghan at the 2024 Toronto International Film Festival (cropped).jpg",
    "title": "Barry Keoghan at the 2024 Toronto International Film Festival (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barry_Keoghan_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg",
    "author": "Kevin Payravi",
    "sourceCredit": "Own work",
    "attribution": "Kevin Payravi / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Ed Sheeran": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Ed_Sheeran-6886_%28cropped_2%29.jpg/330px-Ed_Sheeran-6886_%28cropped_2%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Ed Sheeran-6886 (cropped 2).jpg",
    "title": "Ed Sheeran-6886 (cropped 2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ed_Sheeran-6886_(cropped_2).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Daniel Radcliffe": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/DanielRadcliffe-byPhilipRomano.jpg/330px-DanielRadcliffe-byPhilipRomano.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:DanielRadcliffe-byPhilipRomano.jpg",
    "title": "DanielRadcliffe-byPhilipRomano",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DanielRadcliffe-byPhilipRomano.jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Sydney Sweeney": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Sydney_Sweeney_at_the_2024_Toronto_International_Film_Festival_01_%283x4_cropped_and_rotated%29.jpg/330px-Sydney_Sweeney_at_the_2024_Toronto_International_Film_Festival_01_%283x4_cropped_and_rotated%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Sydney Sweeney at the 2024 Toronto International Film Festival 01 (3x4 cropped and rotated).jpg",
    "title": "Sydney Sweeney at the 2024 Toronto International Film Festival 01 (3x4 cropped and rotated)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sydney_Sweeney_at_the_2024_Toronto_International_Film_Festival_01_(3x4_cropped_and_rotated).jpg",
    "author": "Jay Dixit",
    "sourceCredit": "Own work",
    "attribution": "Jay Dixit / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Megan Fox": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Megan_Fox_-_Jennifer%27s_Body.jpg/330px-Megan_Fox_-_Jennifer%27s_Body.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Megan Fox - Jennifer's Body.jpg",
    "title": "Megan Fox - Jennifer's Body",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Megan_Fox_-_Jennifer%27s_Body.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Margot Robbie": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Margot_Robbie_at_the_Paris_premiere_of_%22Wuthering_Heights%22.jpg/330px-Margot_Robbie_at_the_Paris_premiere_of_%22Wuthering_Heights%22.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Margot Robbie at the Paris premiere of \"Wuthering Heights\".jpg",
    "title": "Margot Robbie at the Paris premiere of \"Wuthering Heights\"",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Margot_Robbie_at_the_Paris_premiere_of_%22Wuthering_Heights%22.jpg",
    "author": "Ondine Goat",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Scarlett Johansson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Scarlett_Johansson-8588.jpg/330px-Scarlett_Johansson-8588.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Scarlett Johansson-8588.jpg",
    "title": "Scarlett Johansson-8588",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scarlett_Johansson-8588.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "Harald Krichel / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Angelina Jolie": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Angelina_Jolie-643531_%28cropped%29.jpg/330px-Angelina_Jolie-643531_%28cropped%29.jpg",
    "width": 329,
    "height": 440,
    "fileTitle": "File:Angelina Jolie-643531 (cropped).jpg",
    "title": "Angelina Jolie-643531 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Angelina_Jolie-643531_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Monica Bellucci": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/Monica_Bellucci-63654.jpg/330px-Monica_Bellucci-63654.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Monica Bellucci-63654.jpg",
    "title": "Monica Bellucci-63654",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Monica_Bellucci-63654.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Adriana Lima": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Adriana_Lima_at_80th_Venice_International_Film_Festival.jpg/330px-Adriana_Lima_at_80th_Venice_International_Film_Festival.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Adriana Lima at 80th Venice International Film Festival.jpg",
    "title": "Adriana Lima at 80th Venice International Film Festival",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Adriana_Lima_at_80th_Venice_International_Film_Festival.jpg",
    "author": "LucaFazPhoto",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Bella Hadid": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Bella_Hadid_at_the_2026_Cannes_Film_Festival_01_%28cropped%29.jpg/330px-Bella_Hadid_at_the_2026_Cannes_Film_Festival_01_%28cropped%29.jpg",
    "width": 330,
    "height": 412,
    "fileTitle": "File:Bella Hadid at the 2026 Cannes Film Festival 01 (cropped).jpg",
    "title": "Bella Hadid at the 2026 Cannes Film Festival 01 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bella_Hadid_at_the_2026_Cannes_Film_Festival_01_(cropped).jpg",
    "author": "Gabriel Hutchinson",
    "sourceCredit": "Own work",
    "attribution": "Gabriel Hutchinson / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Gigi Hadid": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Marina_Ruy_Barbosa_com_Gigi_Hadid_em_Paris_%28Gigi_Hadid%29.jpg/330px-Marina_Ruy_Barbosa_com_Gigi_Hadid_em_Paris_%28Gigi_Hadid%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Marina Ruy Barbosa com Gigi Hadid em Paris (Gigi Hadid).jpg",
    "title": "Marina Ruy Barbosa com Gigi Hadid em Paris (Gigi Hadid)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Ruy_Barbosa_com_Gigi_Hadid_em_Paris_(Gigi_Hadid).jpg",
    "author": "Manuela Muniz Feijó Scarpa",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Emily Ratajkowski": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Kerastase_Club_-_Emily_Ratajkowski_3.png/330px-Kerastase_Club_-_Emily_Ratajkowski_3.png",
    "width": 330,
    "height": 336,
    "fileTitle": "File:Kerastase Club - Emily Ratajkowski 3.png",
    "title": "Kerastase Club - Emily Ratajkowski 3",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kerastase_Club_-_Emily_Ratajkowski_3.png",
    "author": "Yann Tosseyn",
    "sourceCredit": "Vimeo : Kerastase Club ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Zendaya": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Zendaya-byPhilipRomano.jpg/330px-Zendaya-byPhilipRomano.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Zendaya-byPhilipRomano.jpg",
    "title": "Zendaya-byPhilipRomano",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zendaya-byPhilipRomano.jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Ana de Armas": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Ana_de_Armas_%2854462619561%29_%28cropped_3%29.jpg/330px-Ana_de_Armas_%2854462619561%29_%28cropped_3%29.jpg",
    "width": 311,
    "height": 440,
    "fileTitle": "File:Ana de Armas (54462619561) (cropped 3).jpg",
    "title": "Ana de Armas (54462619561) (cropped 3)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ana_de_Armas_(54462619561)_(cropped_3).jpg",
    "author": "Gage Skidmore from Surprise, AZ, United States of America",
    "sourceCredit": "Ana de Armas",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Gal Gadot": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Gal_Gadot_by_Gage_Skidmore_3.jpg/330px-Gal_Gadot_by_Gage_Skidmore_3.jpg",
    "width": 316,
    "height": 440,
    "fileTitle": "File:Gal Gadot by Gage Skidmore 3.jpg",
    "title": "Gal Gadot by Gage Skidmore 3",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gal_Gadot_by_Gage_Skidmore_3.jpg",
    "author": "Gage Skidmore",
    "sourceCredit": "Own work",
    "attribution": "Gage Skidmore",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Dua Lipa": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Dua_Lipa-69798_%28cropped%29.jpg/330px-Dua_Lipa-69798_%28cropped%29.jpg",
    "width": 286,
    "height": 440,
    "fileTitle": "File:Dua Lipa-69798 (cropped).jpg",
    "title": "Dua Lipa-69798 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dua_Lipa-69798_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Emma Stone": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Emma_Stone_at_the_2025_Venice_Film_Festival-6313_%28cropped%29.jpg/330px-Emma_Stone_at_the_2025_Venice_Film_Festival-6313_%28cropped%29.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:Emma Stone at the 2025 Venice Film Festival-6313 (cropped).jpg",
    "title": "Emma Stone at the 2025 Venice Film Festival-6313 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Emma_Stone_at_the_2025_Venice_Film_Festival-6313_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "Harald Krichel / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Emma Watson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Emma_Watson_2013.jpg/330px-Emma_Watson_2013.jpg",
    "width": 328,
    "height": 440,
    "fileTitle": "File:Emma Watson 2013.jpg",
    "title": "Emma Watson 2013",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Emma_Watson_2013.jpg",
    "author": "Georges Biard",
    "sourceCredit": "This image has been extracted from another file",
    "attribution": "Georges Biard",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Natalie Portman": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/NataliePortman.jpg/330px-NataliePortman.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:NataliePortman.jpg",
    "title": "NataliePortman",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:NataliePortman.jpg",
    "author": "Colleen Sturtevant",
    "sourceCredit": "Own work",
    "attribution": "Colleen Sturtevant / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Anya Taylor-Joy": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Anya_Taylor-Joy_at_the_2025_Toronto_International_Film_Festival._06_%28cropped%29.jpg/330px-Anya_Taylor-Joy_at_the_2025_Toronto_International_Film_Festival._06_%28cropped%29.jpg",
    "width": 330,
    "height": 412,
    "fileTitle": "File:Anya Taylor-Joy at the 2025 Toronto International Film Festival. 06 (cropped).jpg",
    "title": "Anya Taylor-Joy at the 2025 Toronto International Film Festival. 06 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anya_Taylor-Joy_at_the_2025_Toronto_International_Film_Festival._06_(cropped).jpg",
    "author": "Sara Komatsu",
    "sourceCredit": "Own work",
    "attribution": "Sara Komatsu / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Beyoncé": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg/330px-Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Beyoncé - Tottenham Hotspur Stadium - 1st June 2023 (10 of 118) (52946364598) (best crop).jpg",
    "title": "Beyoncé - Tottenham Hotspur Stadium - 1st June 2023 (10 of 118) (52946364598) (best crop)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_(10_of_118)_(52946364598)_(best_crop).jpg",
    "author": "Raph_PH",
    "sourceCredit": "BeyonceSpurs010623 (10 of 118)",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Taylor Swift": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png/330px-Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png",
    "width": 309,
    "height": 440,
    "fileTitle": "File:Taylor Swift at the 2023 MTV Video Music Awards (3).png",
    "title": "Taylor Swift at the 2023 MTV Video Music Awards (3)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_(3).png",
    "author": "iHeartRadioCA",
    "sourceCredit": "YouTube : #taylorswift on the #vmas pink carpet – View/save archived versions on archive.org (See specific archived version)",
    "attribution": "iHeartRadioCA",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Selena Gomez": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_%28cropped%29.jpg/330px-Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_%28cropped%29.jpg",
    "width": 326,
    "height": 440,
    "fileTitle": "File:Selena Gomez at the 2024 Toronto International Film Festival 10 (cropped).jpg",
    "title": "Selena Gomez at the 2024 Toronto International Film Festival 10 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_(cropped).jpg",
    "author": "Frank Sun",
    "sourceCredit": "Own work",
    "attribution": "Frank Sun / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Jennifer Lawrence": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Jennifer_Lawrence_in_2018.png/330px-Jennifer_Lawrence_in_2018.png",
    "width": 323,
    "height": 440,
    "fileTitle": "File:Jennifer Lawrence in 2018.png",
    "title": "Jennifer Lawrence in 2018",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jennifer_Lawrence_in_2018.png",
    "author": "MTV International",
    "sourceCredit": "Jennifer Lawrence Reveals Funniest Moments On Set Of Red Sparrow",
    "attribution": "MTV UK",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Florence Pugh": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Florence_Pugh_at_the_2024_Toronto_International_Film_Festival_13_%28cropped_2_%E2%80%93_color_adjusted%29.jpg/330px-Florence_Pugh_at_the_2024_Toronto_International_Film_Festival_13_%28cropped_2_%E2%80%93_color_adjusted%29.jpg",
    "width": 312,
    "height": 440,
    "fileTitle": "File:Florence Pugh at the 2024 Toronto International Film Festival 13 (cropped 2 – color adjusted).jpg",
    "title": "Florence Pugh at the 2024 Toronto International Film Festival 13 (cropped 2 – color adjusted)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Florence_Pugh_at_the_2024_Toronto_International_Film_Festival_13_(cropped_2_%E2%80%93_color_adjusted).jpg",
    "author": "Frank Sun",
    "sourceCredit": "Own work",
    "attribution": "Frank Sun / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Billie Eilish": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg/330px-BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:BillieEilishO2140725-39 - 54665577407 (cropped).jpg",
    "title": "BillieEilishO2140725-39 - 54665577407 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BillieEilishO2140725-39_-_54665577407_(cropped).jpg",
    "author": "Raph_PH",
    "sourceCredit": "https://www.flickr.com/photos/69880995@N04/54665577407/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Kristen Stewart": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Kristen_Stewart_at_WWD_Style_Awards_2026.jpg/330px-Kristen_Stewart_at_WWD_Style_Awards_2026.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Kristen Stewart at WWD Style Awards 2026.jpg",
    "title": "Kristen Stewart at WWD Style Awards 2026",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kristen_Stewart_at_WWD_Style_Awards_2026.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Kate Upton": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Kate_Upton_in_2021.jpg/330px-Kate_Upton_in_2021.jpg",
    "width": 330,
    "height": 395,
    "fileTitle": "File:Kate Upton in 2021.jpg",
    "title": "Kate Upton in 2021",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kate_Upton_in_2021.jpg",
    "author": "Agape Lataillade",
    "sourceCredit": "Vimeo : PEOPLE - Kate Upton, Stars With No Makeup ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Kylie Jenner": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Kylie_Jenner2_%28cropped%29.png/330px-Kylie_Jenner2_%28cropped%29.png",
    "width": 330,
    "height": 404,
    "fileTitle": "File:Kylie Jenner2 (cropped).png",
    "title": "Kylie Jenner2 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kylie_Jenner2_(cropped).png",
    "author": "Hayu",
    "sourceCredit": "https://web.archive.org/web/20180405211728/https://www.youtube.com/watch?v=dP6sVC4gLRk",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Kim Kardashian": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Kim_Kardashian_West_2014.jpg/330px-Kim_Kardashian_West_2014.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Kim Kardashian West 2014.jpg",
    "title": "Kim Kardashian West 2014",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kim_Kardashian_West_2014.jpg",
    "author": "Eva Rinaldi",
    "sourceCredit": "https://www.flickr.com/photos/58820009@N05/15199017476/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Candice Swanepoel": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Candice_Swanepoel_for_Max_Factor_02.jpg/330px-Candice_Swanepoel_for_Max_Factor_02.jpg",
    "width": 330,
    "height": 366,
    "fileTitle": "File:Candice Swanepoel for Max Factor 02.jpg",
    "title": "Candice Swanepoel for Max Factor 02",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Candice_Swanepoel_for_Max_Factor_02.jpg",
    "author": "Nomadic",
    "sourceCredit": "Vimeo : Candice Swanepoel for Max Factor Whipped Creme ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Miranda Kerr": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Miranda_Kerr_-_Abbot_Kinney_2025.jpg/330px-Miranda_Kerr_-_Abbot_Kinney_2025.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Miranda Kerr - Abbot Kinney 2025.jpg",
    "title": "Miranda Kerr - Abbot Kinney 2025",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Miranda_Kerr_-_Abbot_Kinney_2025.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Tyra Banks": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Tyra_Banks_2018_4.png/330px-Tyra_Banks_2018_4.png",
    "width": 319,
    "height": 440,
    "fileTitle": "File:Tyra Banks 2018 4.png",
    "title": "Tyra Banks 2018 4",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tyra_Banks_2018_4.png",
    "author": "Juice Group",
    "sourceCredit": "Vimeo : Tyra Banks Testimonial Dec 13th 2018 - COLOR ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Naomi Campbell": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Naomi_Campbell_Cannes_2018.jpg/330px-Naomi_Campbell_Cannes_2018.jpg",
    "width": 311,
    "height": 440,
    "fileTitle": "File:Naomi Campbell Cannes 2018.jpg",
    "title": "Naomi Campbell Cannes 2018",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Naomi_Campbell_Cannes_2018.jpg",
    "author": "Georges Biard",
    "sourceCredit": "Own work",
    "attribution": "Georges Biard",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Barbara Palvin": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/MKr382323_Barbara_Palvin_%28Cannes_2025%29.jpg/250px-MKr382323_Barbara_Palvin_%28Cannes_2025%29.jpg",
    "width": 247,
    "height": 440,
    "fileTitle": "File:MKr382323 Barbara Palvin (Cannes 2025).jpg",
    "title": "MKr382323 Barbara Palvin (Cannes 2025)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MKr382323_Barbara_Palvin_(Cannes_2025).jpg",
    "author": "Martin Kraft",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Hailee Steinfeld": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Hailee_Steinfeld_by_Gage_Skidmore.jpg/330px-Hailee_Steinfeld_by_Gage_Skidmore.jpg",
    "width": 303,
    "height": 440,
    "fileTitle": "File:Hailee Steinfeld by Gage Skidmore.jpg",
    "title": "Hailee Steinfeld by Gage Skidmore",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hailee_Steinfeld_by_Gage_Skidmore.jpg",
    "author": "Gage Skidmore",
    "sourceCredit": "Own work",
    "attribution": "Gage Skidmore",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Samuel L. Jackson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/SamuelLJackson.jpg/330px-SamuelLJackson.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:SamuelLJackson.jpg",
    "title": "SamuelLJackson",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SamuelLJackson.jpg",
    "author": "Philip Romano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Morgan Freeman": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg/330px-Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Morgan Freeman at The Pentagon on 2 August 2023 - 230802-D-PM193-3363 (cropped).jpg",
    "title": "Morgan Freeman at The Pentagon on 2 August 2023 - 230802-D-PM193-3363 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_(cropped).jpg",
    "author": "U.S. Secretary of Defense",
    "sourceCredit": "https://www.flickr.com/photos/68842444@N03/53090041380/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_(cropped).jpg",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Denzel Washington": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Denzel_Washington_at_the_2025_Cannes_Film_Festival.jpg/330px-Denzel_Washington_at_the_2025_Cannes_Film_Festival.jpg",
    "width": 314,
    "height": 440,
    "fileTitle": "File:Denzel Washington at the 2025 Cannes Film Festival.jpg",
    "title": "Denzel Washington at the 2025 Cannes Film Festival",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Denzel_Washington_at_the_2025_Cannes_Film_Festival.jpg",
    "author": "Gabriel Hutchinson",
    "sourceCredit": "Own work",
    "attribution": "Gabriel Hutchinson / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Tom Hanks": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg/330px-TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg",
    "width": 317,
    "height": 440,
    "fileTitle": "File:TomHanksPrincEdw031223 (11 of 41) (cropped).jpg",
    "title": "TomHanksPrincEdw031223 (11 of 41) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TomHanksPrincEdw031223_(11_of_41)_(cropped).jpg",
    "author": "Raph_PH",
    "sourceCredit": "https://www.flickr.com/photos/raph_ph/53377660110/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Robert Downey Jr.": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/RobertDowneyJr-byPhilipRomano7_%28cropped%29.jpg/330px-RobertDowneyJr-byPhilipRomano7_%28cropped%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:RobertDowneyJr-byPhilipRomano7 (cropped).jpg",
    "title": "RobertDowneyJr-byPhilipRomano7 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:RobertDowneyJr-byPhilipRomano7_(cropped).jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Bryan Cranston": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/BryanCranston-byPhilipRomano_%28cropped%29.jpg/330px-BryanCranston-byPhilipRomano_%28cropped%29.jpg",
    "width": 299,
    "height": 440,
    "fileTitle": "File:BryanCranston-byPhilipRomano (cropped).jpg",
    "title": "BryanCranston-byPhilipRomano (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BryanCranston-byPhilipRomano_(cropped).jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Steve Carell": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Steve_Carell_-_The_40-Year-Old-Virgin.jpg/330px-Steve_Carell_-_The_40-Year-Old-Virgin.jpg",
    "width": 330,
    "height": 413,
    "fileTitle": "File:Steve Carell - The 40-Year-Old-Virgin.jpg",
    "title": "Steve Carell - The 40-Year-Old-Virgin",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Steve_Carell_-_The_40-Year-Old-Virgin.jpg",
    "author": "Kevin Paul",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Danny DeVito": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Danny_DeVito_cropped_and_edited_for_brightness.jpg/330px-Danny_DeVito_cropped_and_edited_for_brightness.jpg",
    "width": 330,
    "height": 385,
    "fileTitle": "File:Danny DeVito cropped and edited for brightness.jpg",
    "title": "Danny DeVito cropped and edited for brightness",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Danny_DeVito_cropped_and_edited_for_brightness.jpg",
    "author": "Gage Skidmore [CC BY-SA 3.0 ( https://creativecommons.org/licenses/by-sa/3.0 )], via Wikimedia Commons",
    "sourceCredit": "File:Danny DeVito by Gage Skidmore 3.jpg",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Nicolas Cage": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Nicolas_Cage_Deauville_2013.jpg/330px-Nicolas_Cage_Deauville_2013.jpg",
    "width": 285,
    "height": 440,
    "fileTitle": "File:Nicolas Cage Deauville 2013.jpg",
    "title": "Nicolas Cage Deauville 2013",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nicolas_Cage_Deauville_2013.jpg",
    "author": "Georges Biard",
    "sourceCredit": "Own work",
    "attribution": "Georges Biard",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Willem Dafoe": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Willem_Dafoe-63668_%28cropped%29.jpg/330px-Willem_Dafoe-63668_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Willem Dafoe-63668 (cropped).jpg",
    "title": "Willem Dafoe-63668 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Willem_Dafoe-63668_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Steve Buscemi": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/SteveBuscemi-byPhilipRomano.jpg/330px-SteveBuscemi-byPhilipRomano.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:SteveBuscemi-byPhilipRomano.jpg",
    "title": "SteveBuscemi-byPhilipRomano",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SteveBuscemi-byPhilipRomano.jpg",
    "author": "PhilipRomanoPhoto",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "James Corden": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/James_Corden_at_2015_PaleyFest_%28cropped%29.jpg/330px-James_Corden_at_2015_PaleyFest_%28cropped%29.jpg",
    "width": 318,
    "height": 440,
    "fileTitle": "File:James Corden at 2015 PaleyFest (cropped).jpg",
    "title": "James Corden at 2015 PaleyFest (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:James_Corden_at_2015_PaleyFest_(cropped).jpg",
    "author": "iDominick",
    "sourceCredit": "https://www.flickr.com/photos/82924988@N05/16364434933/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jimmy Kimmel": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Jimmy_Kimmel_June_2022.jpg/330px-Jimmy_Kimmel_June_2022.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Jimmy Kimmel June 2022.jpg",
    "title": "Jimmy Kimmel June 2022",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jimmy_Kimmel_June_2022.jpg",
    "author": "Erin Scott",
    "sourceCredit": "P20220608ES-0526",
    "attribution": "",
    "copyrightNotice": "",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Jimmy_Kimmel_June_2022.jpg",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jimmy Fallon": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Jimmy_Fallon-TTL_4575_%2811046141004%29_%285x7_cropped_and_rotated%29.jpg/330px-Jimmy_Fallon-TTL_4575_%2811046141004%29_%285x7_cropped_and_rotated%29.jpg",
    "width": 314,
    "height": 440,
    "fileTitle": "File:Jimmy Fallon-TTL 4575 (11046141004) (5x7 cropped and rotated).jpg",
    "title": "Jimmy Fallon-TTL 4575 (11046141004) (5x7 cropped and rotated)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jimmy_Fallon-TTL_4575_(11046141004)_(5x7_cropped_and_rotated).jpg",
    "author": "Montclair Film",
    "sourceCredit": "TTL_4575",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Conan O'Brien": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Conan_O%27Brien_at_the_2025_Sundance_Film_Festival_03_%28cropped%29.jpg/330px-Conan_O%27Brien_at_the_2025_Sundance_Film_Festival_03_%28cropped%29.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:Conan O'Brien at the 2025 Sundance Film Festival 03 (cropped).jpg",
    "title": "Conan O'Brien at the 2025 Sundance Film Festival 03 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Conan_O%27Brien_at_the_2025_Sundance_Film_Festival_03_(cropped).jpg",
    "author": "Adam Chitayat",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Kevin Hart": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Kevin_Hart_2014_%28cropped_2%29.jpg/330px-Kevin_Hart_2014_%28cropped_2%29.jpg",
    "width": 325,
    "height": 440,
    "fileTitle": "File:Kevin Hart 2014 (cropped 2).jpg",
    "title": "Kevin Hart 2014 (cropped 2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kevin_Hart_2014_(cropped_2).jpg",
    "author": "Eva Rinaldi",
    "sourceCredit": "https://www.flickr.com/photos/evarinaldiphotography/12966419535/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Seth Rogen": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Seth_Rogen_at_the_Sundance_Film_Festival_2026_%28cropped%29.jpg/330px-Seth_Rogen_at_the_Sundance_Film_Festival_2026_%28cropped%29.jpg",
    "width": 330,
    "height": 412,
    "fileTitle": "File:Seth Rogen at the Sundance Film Festival 2026 (cropped).jpg",
    "title": "Seth Rogen at the Sundance Film Festival 2026 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Seth_Rogen_at_the_Sundance_Film_Festival_2026_(cropped).jpg",
    "author": "Colleen Sturtevant",
    "sourceCredit": "Own work",
    "attribution": "Colleen Sturtevant / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Jonah Hill": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Jonah_Hill-4939_%28cropped%29_%28cropped%29.jpg/330px-Jonah_Hill-4939_%28cropped%29_%28cropped%29.jpg",
    "width": 330,
    "height": 434,
    "fileTitle": "File:Jonah Hill-4939 (cropped) (cropped).jpg",
    "title": "Jonah Hill-4939 (cropped) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jonah_Hill-4939_(cropped)_(cropped).jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Will Ferrell": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Will_Ferrell_at_the_2024_Toronto_International_Film_Festival_5_%28cropped%29.jpg/330px-Will_Ferrell_at_the_2024_Toronto_International_Film_Festival_5_%28cropped%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Will Ferrell at the 2024 Toronto International Film Festival 5 (cropped).jpg",
    "title": "Will Ferrell at the 2024 Toronto International Film Festival 5 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Will_Ferrell_at_the_2024_Toronto_International_Film_Festival_5_(cropped).jpg",
    "author": "Adam Chitayat",
    "sourceCredit": "Own work",
    "attribution": "Adam Chitayat / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Jack Black": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/TenaciousDO2160623_%2838_of_62%29_Jack_Black.jpg/330px-TenaciousDO2160623_%2838_of_62%29_Jack_Black.jpg",
    "width": 315,
    "height": 440,
    "fileTitle": "File:TenaciousDO2160623 (38 of 62) Jack Black.jpg",
    "title": "TenaciousDO2160623 (38 of 62) Jack Black",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TenaciousDO2160623_(38_of_62)_Jack_Black.jpg",
    "author": "Raph_PH",
    "sourceCredit": "TenaciousDO2160623 (38 of 62)",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "MrBeast": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/MrBeast_in_2026_%28cropped_4%29.png/330px-MrBeast_in_2026_%28cropped_4%29.png",
    "width": 330,
    "height": 440,
    "fileTitle": "File:MrBeast in 2026 (cropped 4).png",
    "title": "MrBeast in 2026 (cropped 4)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MrBeast_in_2026_(cropped_4).png",
    "author": "Tyren Redd",
    "sourceCredit": "David Soled",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jake Paul": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Jake_Paul_March_2026_%283x4_cropped%29.jpg/330px-Jake_Paul_March_2026_%283x4_cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Jake Paul March 2026 (3x4 cropped).jpg",
    "title": "Jake Paul March 2026 (3x4 cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jake_Paul_March_2026_(3x4_cropped).jpg",
    "author": "The White House",
    "sourceCredit": "https://www.flickr.com/photos/whitehouse/55145916738/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Jake_Paul_March_2026_(3x4_cropped).jpg",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Logan Paul": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Logan_Paul_RR25_%28cropped%29.jpg/330px-Logan_Paul_RR25_%28cropped%29.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:Logan Paul RR25 (cropped).jpg",
    "title": "Logan Paul RR25 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Logan_Paul_RR25_(cropped).jpg",
    "author": "Diego Serrano",
    "sourceCredit": "WWE Royal Rumble 2025",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "KSI": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/KSI_in_2024_%282%29.png/330px-KSI_in_2024_%282%29.png",
    "width": 316,
    "height": 440,
    "fileTitle": "File:KSI in 2024 (2).png",
    "title": "KSI in 2024 (2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:KSI_in_2024_(2).png",
    "author": "MILLION DOLLAZ WORTH OF GAME",
    "sourceCredit": "YouTube : KSI: MILLION DOLLAZ WORTH OF GAME EPISODE 304 – View/save archived versions on archive.org",
    "attribution": "MILLION DOLLAZ WORTH OF GAME",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Valkyrae": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Valkyrae_in_2023_%28cropped%29.png/330px-Valkyrae_in_2023_%28cropped%29.png",
    "width": 330,
    "height": 421,
    "fileTitle": "File:Valkyrae in 2023 (cropped).png",
    "title": "Valkyrae in 2023 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Valkyrae_in_2023_(cropped).png",
    "author": "Gymshark",
    "sourceCredit": "YouTube : VALKYRAE's DREAM PLAYER 2! (Time: 19) – View/save archived versions on archive.org",
    "attribution": "Gymshark",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "LeBron James": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/330px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg",
    "width": 330,
    "height": 382,
    "fileTitle": "File:LeBron James (51959977144) (cropped2).jpg",
    "title": "LeBron James (51959977144) (cropped2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeBron_James_(51959977144)_(cropped2).jpg",
    "author": "Erik Drost",
    "sourceCredit": "https://www.flickr.com/photos/edrost88/51959977144/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Patrick Mahomes": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Patrick_Mahomes_%2851615475056%29.jpg/330px-Patrick_Mahomes_%2851615475056%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Patrick Mahomes (51615475056).jpg",
    "title": "Patrick Mahomes (51615475056)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Patrick_Mahomes_(51615475056).jpg",
    "author": "All-Pro Reels from District of Columbia, USA",
    "sourceCredit": "Patrick Mahomes",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "trademarked",
    "verifiedAt": "2026-09-07"
  },
  "Serena Williams": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg/330px-Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg",
    "width": 267,
    "height": 440,
    "fileTitle": "File:Guests at the 2026 Met Gala 209 (cropped).jpg",
    "title": "Guests at the 2026 Met Gala 209 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Guests_at_the_2026_Met_Gala_209_(cropped).jpg",
    "author": "SWinxy",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Simone Biles": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Simone_Biles_National_Team_2024.jpg/330px-Simone_Biles_National_Team_2024.jpg",
    "width": 305,
    "height": 440,
    "fileTitle": "File:Simone Biles National Team 2024.jpg",
    "title": "Simone Biles National Team 2024",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Simone_Biles_National_Team_2024.jpg",
    "author": "Ocoudis",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Paige Spiranac": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Golfer_Paige_Spiranac_%28cropped%29.jpg/330px-Golfer_Paige_Spiranac_%28cropped%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Golfer Paige Spiranac (cropped).jpg",
    "title": "Golfer Paige Spiranac (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Golfer_Paige_Spiranac_(cropped).jpg",
    "author": "Lexie Mitchell",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Sydney McLaughlin-Levrone": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Sydney_McLaughlin_Oregon_2022%282%29.jpg/330px-Sydney_McLaughlin_Oregon_2022%282%29.jpg",
    "width": 330,
    "height": 415,
    "fileTitle": "File:Sydney McLaughlin Oregon 2022(2).jpg",
    "title": "Sydney McLaughlin Oregon 2022(2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sydney_McLaughlin_Oregon_2022(2).jpg",
    "author": "Erik van Leeuwen (bron: Wikipedia)",
    "sourceCredit": "cropped",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Eugenie Bouchard": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Bouchard_WMQ23_%2853061135097%29.jpg/330px-Bouchard_WMQ23_%2853061135097%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:Bouchard WMQ23 (53061135097).jpg",
    "title": "Bouchard WMQ23 (53061135097)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bouchard_WMQ23_(53061135097).jpg",
    "author": "si.robi",
    "sourceCredit": "Bouchard WMQ23",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Melissa McCarthy": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Melissa_McCarthy_in_2018_%28cropped%29.jpg/330px-Melissa_McCarthy_in_2018_%28cropped%29.jpg",
    "width": 309,
    "height": 440,
    "fileTitle": "File:Melissa McCarthy in 2018 (cropped).jpg",
    "title": "Melissa McCarthy in 2018 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Melissa_McCarthy_in_2018_(cropped).jpg",
    "author": "https://www.flickr.com/photos/greg2600",
    "sourceCredit": "https://www.flickr.com/photos/greg2600/45574562892",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Amy Schumer": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Amy_Schumer_by_Mario_Santor.jpg/330px-Amy_Schumer_by_Mario_Santor.jpg",
    "width": 292,
    "height": 440,
    "fileTitle": "File:Amy Schumer by Mario Santor.jpg",
    "title": "Amy Schumer by Mario Santor",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Amy_Schumer_by_Mario_Santor.jpg",
    "author": "Mario Santor",
    "sourceCredit": "evityentertainmentgroup.com",
    "attribution": "Photograph by Mario Santor",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Rebel Wilson": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Rebel_Wilson_%286707611099%29_%28cropped%29.jpg/330px-Rebel_Wilson_%286707611099%29_%28cropped%29.jpg",
    "width": 308,
    "height": 440,
    "fileTitle": "File:Rebel Wilson (6707611099) (cropped).jpg",
    "title": "Rebel Wilson (6707611099) (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rebel_Wilson_(6707611099)_(cropped).jpg",
    "author": "Eva Rinaldi",
    "sourceCredit": "Rebel Wilson",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Whoopi Goldberg": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/WhoopiGoldberg-byPhilipRomano2.jpg/330px-WhoopiGoldberg-byPhilipRomano2.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:WhoopiGoldberg-byPhilipRomano2.jpg",
    "title": "WhoopiGoldberg-byPhilipRomano2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:WhoopiGoldberg-byPhilipRomano2.jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Oprah Winfrey": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Oprah_Winfrey_2016.jpg/330px-Oprah_Winfrey_2016.jpg",
    "width": 304,
    "height": 440,
    "fileTitle": "File:Oprah Winfrey 2016.jpg",
    "title": "Oprah Winfrey 2016",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oprah_Winfrey_2016.jpg",
    "author": "US Embassy South Africa",
    "sourceCredit": "https://www.flickr.com/photos/usembassysa/30637612874/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Oprah_Winfrey_2016.jpg",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Lizzo": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Lizzo_September_2025.png/330px-Lizzo_September_2025.png",
    "width": 323,
    "height": 440,
    "fileTitle": "File:Lizzo September 2025.png",
    "title": "Lizzo September 2025",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lizzo_September_2025.png",
    "author": "MILLION DOLLAZ WORTH OF GAME",
    "sourceCredit": "YouTube : LIZZO: MILLION DOLLAZ WORTH OF GAME EPISODE 343 – View/save archived versions on archive.org",
    "attribution": "MILLION DOLLAZ WORTH OF GAME",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Oscar Isaac": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Oscar_Isaac_at_82nd_Venice_International_Film_Festival-1_%28cropped%29.jpg/330px-Oscar_Isaac_at_82nd_Venice_International_Film_Festival-1_%28cropped%29.jpg",
    "width": 324,
    "height": 440,
    "fileTitle": "File:Oscar Isaac at 82nd Venice International Film Festival-1 (cropped).jpg",
    "title": "Oscar Isaac at 82nd Venice International Film Festival-1 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oscar_Isaac_at_82nd_Venice_International_Film_Festival-1_(cropped).jpg",
    "author": "LucaFazPhoto",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Rami Malek": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Rami_Malek_at_the_2026_Cannes_Film_Festival-69448.jpg/330px-Rami_Malek_at_the_2026_Cannes_Film_Festival-69448.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:Rami Malek at the 2026 Cannes Film Festival-69448.jpg",
    "title": "Rami Malek at the 2026 Cannes Film Festival-69448",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rami_Malek_at_the_2026_Cannes_Film_Festival-69448.jpg",
    "author": "Harald Krichel",
    "sourceCredit": "Own work",
    "attribution": "Harald Krichel / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Paul Mescal": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Paul_Mescal_at_the_Toronto_International_Film_Festival_in_2025_2_%28cropped_2%29.jpg/330px-Paul_Mescal_at_the_Toronto_International_Film_Festival_in_2025_2_%28cropped_2%29.jpg",
    "width": 326,
    "height": 440,
    "fileTitle": "File:Paul Mescal at the Toronto International Film Festival in 2025 2 (cropped 2).jpg",
    "title": "Paul Mescal at the Toronto International Film Festival in 2025 2 (cropped 2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paul_Mescal_at_the_Toronto_International_Film_Festival_in_2025_2_(cropped_2).jpg",
    "author": "Jay Dixit",
    "sourceCredit": "Own work",
    "attribution": "Jay Dixit / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Austin Butler": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Austin_Butler_at_the_2025_Cannes_Film_Festival_02.jpg/330px-Austin_Butler_at_the_2025_Cannes_Film_Festival_02.jpg",
    "width": 314,
    "height": 440,
    "fileTitle": "File:Austin Butler at the 2025 Cannes Film Festival 02.jpg",
    "title": "Austin Butler at the 2025 Cannes Film Festival 02",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Austin_Butler_at_the_2025_Cannes_Film_Festival_02.jpg",
    "author": "Gabriel Hutchinson",
    "sourceCredit": "Own work",
    "attribution": "Gabriel Hutchinson / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Jacob Elordi": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/JacobElordi-TIFF2025-01_%28cropped_2%29.png/330px-JacobElordi-TIFF2025-01_%28cropped_2%29.png",
    "width": 320,
    "height": 440,
    "fileTitle": "File:JacobElordi-TIFF2025-01 (cropped 2).png",
    "title": "JacobElordi-TIFF2025-01 (cropped 2)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:JacobElordi-TIFF2025-01_(cropped_2).png",
    "author": "JoshPopov",
    "sourceCredit": "Own work",
    "attribution": "JoshPopov / WikiPortraits",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Steven Yeun": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Steven_Yeun_at_the_2025_Sundance_Film_Festival_%28cropped%29.jpg/330px-Steven_Yeun_at_the_2025_Sundance_Film_Festival_%28cropped%29.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:Steven Yeun at the 2025 Sundance Film Festival (cropped).jpg",
    "title": "Steven Yeun at the 2025 Sundance Film Festival (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Steven_Yeun_at_the_2025_Sundance_Film_Festival_(cropped).jpg",
    "author": "Everwest",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Viola Davis": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Viola_Davis_at_the_Air_Premiere_at_SXSW_%28cropped%29.jpg/330px-Viola_Davis_at_the_Air_Premiere_at_SXSW_%28cropped%29.jpg",
    "width": 305,
    "height": 440,
    "fileTitle": "File:Viola Davis at the Air Premiere at SXSW (cropped).jpg",
    "title": "Viola Davis at the Air Premiere at SXSW (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Viola_Davis_at_the_Air_Premiere_at_SXSW_(cropped).jpg",
    "author": "Nomoretitanic",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Charlize Theron": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/CharlizeTheron-byPhilipRomano2.jpg/330px-CharlizeTheron-byPhilipRomano2.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:CharlizeTheron-byPhilipRomano2.jpg",
    "title": "CharlizeTheron-byPhilipRomano2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:CharlizeTheron-byPhilipRomano2.jpg",
    "author": "PhilipRomano",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Constance Wu": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/ConstanceWu-byPhilipRomano.jpg/330px-ConstanceWu-byPhilipRomano.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:ConstanceWu-byPhilipRomano.jpg",
    "title": "ConstanceWu-byPhilipRomano",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ConstanceWu-byPhilipRomano.jpg",
    "author": "PhilipRomanoPhoto",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Zoë Kravitz": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Zoe_Kravitz_2020_dvna_studio.jpg/330px-Zoe_Kravitz_2020_dvna_studio.jpg",
    "width": 330,
    "height": 439,
    "fileTitle": "File:Zoe Kravitz 2020 dvna studio.jpg",
    "title": "Zoe Kravitz 2020 dvna studio",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zoe_Kravitz_2020_dvna_studio.jpg",
    "author": "dvna creative agency: https://www.dvna.fr/",
    "sourceCredit": "Vimeo : 415931594 ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Jodie Comer": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Jodie_Comer%2C_The_Bikeriders_premiere.jpg/330px-Jodie_Comer%2C_The_Bikeriders_premiere.jpg",
    "width": 295,
    "height": 440,
    "fileTitle": "File:Jodie Comer, The Bikeriders premiere.jpg",
    "title": "Jodie Comer, The Bikeriders premiere",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jodie_Comer,_The_Bikeriders_premiere.jpg",
    "author": "https://www.flickr.com/photos/drlovell/",
    "sourceCredit": "https://www.flickr.com/photos/drlovell/53793951424/in/album-72177720317950584/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Saoirse Ronan": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/MKr349648_Saoirse_Ronan_%28The_Outrun%2C_Berlinale_2024%29.jpg/330px-MKr349648_Saoirse_Ronan_%28The_Outrun%2C_Berlinale_2024%29.jpg",
    "width": 293,
    "height": 440,
    "fileTitle": "File:MKr349648 Saoirse Ronan (The Outrun, Berlinale 2024).jpg",
    "title": "MKr349648 Saoirse Ronan (The Outrun, Berlinale 2024)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MKr349648_Saoirse_Ronan_(The_Outrun,_Berlinale_2024).jpg",
    "author": "Martin Kraft",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "personality",
    "verifiedAt": "2026-09-07"
  },
  "Bad Bunny": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Bad_Bunny_2019_by_Glenn_Francis_%28cropped%29.jpg/330px-Bad_Bunny_2019_by_Glenn_Francis_%28cropped%29.jpg",
    "width": 291,
    "height": 440,
    "fileTitle": "File:Bad Bunny 2019 by Glenn Francis (cropped).jpg",
    "title": "Bad Bunny 2019 by Glenn Francis (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bad_Bunny_2019_by_Glenn_Francis_(cropped).jpg",
    "author": "Toglenn",
    "sourceCredit": "Own work",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Frank Ocean": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Frank_Ocean_2022_Blonded.jpg/330px-Frank_Ocean_2022_Blonded.jpg",
    "width": 330,
    "height": 412,
    "fileTitle": "File:Frank Ocean 2022 Blonded.jpg",
    "title": "Frank Ocean 2022 Blonded",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Frank_Ocean_2022_Blonded.jpg",
    "author": "Andras Ladocsi",
    "sourceCredit": "https://blonded.co/blogs/p/frank-ocean-by-andras-ladocsi Blonded website- listed as: \"Frank Ocean by Andras Ladocsi and Frank Ocean is licensed under CC BY-SA 4.0\"",
    "attribution": "Andras Ladocsi",
    "copyrightNotice": "",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Doja Cat": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Doja_Cat_x_Amazon1.1_%28cropped%29.jpg/330px-Doja_Cat_x_Amazon1.1_%28cropped%29.jpg",
    "width": 330,
    "height": 438,
    "fileTitle": "File:Doja Cat x Amazon1.1 (cropped).jpg",
    "title": "Doja Cat x Amazon1.1 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Doja_Cat_x_Amazon1.1_(cropped).jpg",
    "author": "Nate the Director",
    "sourceCredit": "Vimeo : Doja Cat x Amazon ( view archived source )",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Rosalía": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/2023-11-16_Gala_de_los_Latin_Grammy%2C_27_%28cropped%29.jpg/330px-2023-11-16_Gala_de_los_Latin_Grammy%2C_27_%28cropped%29.jpg",
    "width": 330,
    "height": 440,
    "fileTitle": "File:2023-11-16 Gala de los Latin Grammy, 27 (cropped).jpg",
    "title": "2023-11-16 Gala de los Latin Grammy, 27 (cropped)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023-11-16_Gala_de_los_Latin_Grammy,_27_(cropped).jpg",
    "author": "Junta de Andalucía",
    "sourceCredit": "https://www.flickr.com/photos/68782198@N02/53347397631/",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  },
  "Israel Adesanya": {
    "src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Israel_Adesanya_at_UFC_230.jpg/330px-Israel_Adesanya_at_UFC_230.jpg",
    "width": 330,
    "height": 420,
    "fileTitle": "File:Israel Adesanya at UFC 230.jpg",
    "title": "Israel Adesanya at UFC 230",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Israel_Adesanya_at_UFC_230.jpg",
    "author": "MMMAnytt",
    "sourceCredit": "YouTube : https://www.youtube.com/watch?v=TGgGh5VSoH8&list=PLuHnK1AEEb9s4luYfKNcBvtCH8WAonNAz&index=18 – View/save archived versions on archive.org at 0:07 cropped",
    "attribution": "",
    "copyrightNotice": "",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "restrictions": "",
    "verifiedAt": "2026-09-07"
  }
};

export const WITHHELD_PORTRAITS: Readonly<Record<string, { fileTitle: string; reason: string }>> = {
  "Kendall Jenner": {
    "fileTitle": "File:Kendall Jenner for Adanola 2 (cropped).jpg",
    "reason": "Bounded thumbnail unavailable"
  },
  "Ninja (gamer)": {
    "fileTitle": "File:Krystalogy, Jess, Ninja, and Typical Gamer relaxing in the State Farm Gamerhood (52899874282) (3x4 cropped on Ninja and rotated).jpg",
    "reason": "Bounded thumbnail unavailable"
  },
  "Sha'Carri Richardson": {
    "fileTitle": "File:Sha'Carri Richardson Budapest 2023 (cropped).jpg",
    "reason": "License requires separate review"
  }
};

export function celebrityPortrait(name: string): CelebrityPortrait | null {
  return Object.prototype.hasOwnProperty.call(PORTRAITS, name) ? PORTRAITS[name] : null;
}

export function celebrityPortraitSources(): Record<string, string> {
  return Object.fromEntries([
    ...Object.entries(PORTRAITS).map(([name, portrait]) => [name, portrait.fileTitle]),
    ...Object.entries(WITHHELD_PORTRAITS).map(([name, entry]) => [name, entry.fileTitle]),
  ]);
}
