// The TABLE below is GENERATED by tools/reliability.mjs — do not hand-edit it.
// The tool prints the table to stdout and a human pastes it in, so when you do
// that, replace the object literal only: the import and the accessor beneath it
// are hand-written and the fallback chain in reliabilityOf is load-bearing.
//
// Per-metric reliability: the share of a metric's observed variance that is
// real between-person signal rather than photo-to-photo noise, measured as
// 1 - (within-person SD / population SD)². Estimated across 90 photos of 14
// people (multiple photos each, varying year, lighting, expression, camera).
//
// A metric at 0 varies as much between two photos of ONE person as it does
// across the whole population — it carries no information about the face, so
// it must not move the score. Scoring multiplies each metric's weight by this
// value; the measurement is still displayed, flagged as indicative.
//
// Most zeros are structural, not incidental: metrics built on small distances
// (nose width, eye aperture, inner-canthal spacing) or on left-right
// differences amplify landmark jitter, and fWHR/jaw angles move with weight
// and expression rather than bone.
import { RELIABILITY_SEED } from "./reliabilitySeed.js";

export const RELIABILITY: Record<string, number> = {
browPosition: 0.52,
  browTilt: 0.70,
  canthalAsymmetry: 0.15,
  canthalTilt: 0.57,
  cheekboneHeight: 0.46,
  chinHeightRatio: 0.03,
  chinWidthRatio: 0.44,
  eyeAspectRatio: 0.32,
  eyeMouthParallel: 0.00,
  eyeSeparationRatio: 0.00,
  facialIndex: 0.55,
  fifthsEyeRatio: 0.67,
  fwhr: 0.00,
  gonialProxy: 0.25,
  intercanthalEyeWidth: 0.73,
  jawCheekRatio: 0.47,
  jawFrontalAngle: 0.10,
  lipHeightLowerThird: 0.23,
  lipRatio: 0.74,
  lowerFacePct: 0.35,
  middleLowerBalance: 0.62,
  midfaceRatio: 0.59,
  midlineDeviation: 0.67,
  mirrorDeviation: 0.02,
  mouthCornerTilt: 0.60,
  mouthIPD: 0.00,
  nasalIndex: 0.00,
  noseIntercanthal: 0.14,
  noseMouthRatio: 0.11,
  philtrumChinRatio: 0.69,
  topThirdEst: 0.62,
};

// Below this, a metric is shown as "indicative" rather than scored.
export const RELIABLE_MIN = 0.15;

export function reliabilityOf(id: string): number {
  // The generated table first, then the hand-seeded one for metrics it has
  // never seen. The 0.5 fallback stays for anything in neither, but nothing
  // should be reaching it — see reliabilitySeed.ts for why a silent 0.5 is the
  // wrong answer for a measurement nobody has tested yet.
  return RELIABILITY[id] ?? RELIABILITY_SEED[id] ?? 0.5;
}
