// Generate src/engine/aggNorm.ts: the mean/SD of every aggregate z across the
// general-population reference set. Applying these anchors the score scale so
// the population median is exactly 5.0 and 1 SD is exactly 1.3 score points.
//
// Run AFTER apply.mjs (distributions must already be in place), then rebuild.
import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const APP_DIR = "/home/user/truemax";
const DATA = process.env.TM_DATA ?? new URL("../.calib/", import.meta.url).pathname;
const pop = JSON.parse(readFileSync(DATA + "pop-manifest.json", "utf8"));

// Same envelope the calibration pool uses
const GATE = { yaw: 25, pitch: 22, smile: 0.7 };

const server = spawn("npx", ["vite", "preview", "--port", "4186", "--strictPort"], { cwd: APP_DIR, stdio: "ignore" });
await new Promise((r) => setTimeout(r, 2500));
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });

const bySex = { male: [], female: [] };
try {
  const page = await browser.newPage();
  await page.goto("http://localhost:4186/");
  await page.waitForSelector("#engine-status.ready", { timeout: 30000 });

  for (const { name, sex, file } of pop) {
    try {
      const url = `data:image/jpeg;base64,${readFileSync(file).toString("base64")}`;
      const r = await page.evaluate(
        async ([u, s]) => {
          const m = await window.__truemaxMeasureFull(u, s);
          return m.faceFound ? { z: m.zScores, yaw: m.yaw, pitch: m.pitch, smile: m.smile } : null;
        },
        [url, sex],
      );
      if (!r) continue;
      if (Math.abs(r.yaw) > GATE.yaw || Math.abs(r.pitch) > GATE.pitch || r.smile > GATE.smile) continue;
      bySex[sex].push(r.z);
    } catch {
      console.log(`skip ${name}`);
    }
  }
} finally {
  await browser.close();
  server.kill();
}

// Median/MAD rather than mean/SD: the aggregate z is skewed, so anchoring on
// the mean leaves the population MEDIAN off 5.0 — and the median is what the
// "5.0 = 50th percentile" promise is about.
const median = (a) => {
  const s = [...a].sort((x, y) => x - y);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const mean = median;
// Scale uses the plain SD, not MAD: on a sample this size MAD underestimates
// spread on skewed data, which would make scores hypersensitive (a top face
// reaching 9.5 instead of the ~6.5 that "genuinely rare" should mean).
const sd = (a) => {
  const m = a.reduce((x, y) => x + y, 0) / a.length;
  return Math.sqrt(a.reduce((x, y) => x + (y - m) ** 2, 0) / Math.max(1, a.length - 1));
};

const out = { male: {}, female: {} };
for (const sex of ["male", "female"]) {
  const rows = bySex[sex];
  console.log(`${sex}: ${rows.length} reference faces`);
  if (rows.length < 6) {
    console.log(`  too few — leaving ${sex} unnormalized`);
    continue;
  }
  for (const key of Object.keys(rows[0])) {
    const vals = rows.map((r) => r[key]).filter(Number.isFinite);
    // Keep the SD from collapsing on a thin sample
    out[sex][key] = { mean: +mean(vals).toFixed(4), sd: +Math.max(0.35, sd(vals)).toFixed(4) };
  }
}

const body = ["male", "female"]
  .map((sex) => {
    const rows = Object.entries(out[sex])
      .map(([k, v]) => `    ${JSON.stringify(k)}: { mean: ${v.mean}, sd: ${v.sd} },`)
      .join("\n");
    return `  ${sex}: {\n${rows}\n  },`;
  })
  .join("\n");

writeFileSync(
  APP_DIR + "/src/engine/aggNorm.ts",
  `import type { Sex } from "./types.ts";

// GENERATED by tools/normalize.mjs — do not hand-edit.
//
// Mean/SD of each aggregate z across the general-population reference set
// (people notable for their work, not their appearance). Applying these makes
// the population median score exactly 5.0 and one SD exactly 1.3 score
// points, so percentile claims are anchored to a real sample.
export const AGG_NORM: Record<Sex, Record<string, { mean: number; sd: number }>> = {
${body}
};
`,
);
console.log("wrote src/engine/aggNorm.ts");
process.exit(0);
