export const POPULATION2 = [
  ["Kirsten Gillibrand","female"],["Tammy Baldwin","female"],["Maggie Hassan","female"],
  ["Jeanne Shaheen","female"],["Catherine Cortez Masto","female"],["Jacky Rosen","female"],
  ["Lisa Murkowski","female"],["Susan Collins","female"],["Shelley Moore Capito","female"],
  ["Marsha Blackburn","female"],["Cynthia Lummis","female"],["Joni Ernst","female"],
  ["Laphonza Butler","female"],["Alex Padilla","male"],["Mazie Hirono","female"],
  ["Patty Murray","female"],["Maria Cantwell","female"],["Debbie Stabenow","female"],
  ["Amy Coney Barrett","female"],["Elena Kagan","female"],["Sonia Sotomayor","female"],
  ["Ketanji Brown Jackson","female"],["Karine Jean-Pierre","female"],["Jen Psaki","female"],
  ["Gina Raimondo","female"],["Marcia Fudge","female"],["Isabel Guzman","female"],
  ["Cecilia Rouse","female"],["Neera Tanden","female"],["Samantha Power","female"],
  ["Wendy Sherman","female"],["Bonnie Jenkins","female"],["Kathy Hochul","female"],
  ["Maura Healey","female"],["Laura Kelly","female"],["Michelle Lujan Grisham","female"],
  ["Kate Brown","female"],["Janet Mills","female"],["Kay Ivey","female"],
  ["Kristi Noem","female"],["Sarah Huckabee Sanders","female"],["Katie Hobbs","female"],
  ["Tina Kotek","female"],["Wes Moore","male"],["Andy Beshear","male"],
  ["Josh Shapiro","male"],["Jared Polis","male"],["Phil Murphy","male"],
  ["JB Pritzker","male"],["Tim Walz","male"],["Roy Cooper","male"],
  ["Brian Kemp","male"],["Greg Abbott","male"],["Spencer Cox","male"],
  ["Ron Wyden","male"],["Chris Coons","male"],["Brian Schatz","male"],
  ["Chris Murphy","male"],["Martin Heinrich","male"],["Michael Bennet","male"],
];
