-- Durable Coach Max conversations and plan memory.
--
-- Photographs, landmarks and complete scan payloads deliberately do not live
-- here. A conversation stores only the words the member and Max exchanged;
-- plan memory stores only the explicit action label and its state.

create table public.max_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  source text not null default 'dashboard'
    constraint max_conversations_source_check check (source in ('dashboard', 'post_analysis')),
  title text not null default 'New chat'
    constraint max_conversations_title_length check (char_length(title) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint max_conversations_id_user_unique unique (id, user_id)
);

create index max_conversations_owner_recent_idx
  on public.max_conversations (user_id, last_message_at desc, id)
  where archived_at is null;

create table public.max_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null constraint max_messages_role_check check (role in ('user', 'assistant')),
  content text not null
    constraint max_messages_content_length check (char_length(content) between 1 and 8000),
  client_turn_id uuid,
  created_at timestamptz not null default now(),
  constraint max_messages_conversation_owner_fk
    foreign key (conversation_id, user_id)
    references public.max_conversations (id, user_id)
    on delete cascade
);

create index max_messages_conversation_order_idx
  on public.max_messages (conversation_id, id);

create unique index max_messages_client_turn_unique
  on public.max_messages (conversation_id, client_turn_id)
  where client_turn_id is not null;

create table public.max_plan_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null
    constraint max_plan_items_title_length check (char_length(title) between 1 and 120),
  normalized_title text not null
    constraint max_plan_items_normalized_length check (char_length(normalized_title) between 1 and 120),
  category text not null default 'other'
    constraint max_plan_items_category_check
      check (category in ('product', 'nutrition', 'training', 'skin', 'grooming', 'habit', 'other')),
  status text not null default 'active'
    constraint max_plan_items_status_check
      check (status in ('active', 'paused', 'not_working', 'completed', 'replaced')),
  notes text not null default ''
    constraint max_plan_items_notes_length check (char_length(notes) <= 1000),
  source_conversation_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint max_plan_items_owner_title_unique unique (user_id, normalized_title),
  constraint max_plan_items_conversation_owner_fk
    foreign key (source_conversation_id, user_id)
    references public.max_conversations (id, user_id)
    on delete set null (source_conversation_id)
);

create index max_plan_items_owner_status_idx
  on public.max_plan_items (user_id, status, updated_at desc);

alter table public.max_conversations enable row level security;
alter table public.max_messages enable row level security;
alter table public.max_plan_items enable row level security;

-- Keep the browser out of the raw tables. Reads and writes go through the
-- authenticated API, which checks Max access and scopes every query to the
-- caller before the service-role client is used.
revoke all on table public.max_conversations from public, anon, authenticated;
revoke all on table public.max_messages from public, anon, authenticated;
revoke all on table public.max_plan_items from public, anon, authenticated;
revoke all on sequence public.max_messages_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.max_conversations to service_role;
grant select, insert, update, delete on table public.max_messages to service_role;
grant select, insert, update, delete on table public.max_plan_items to service_role;
grant usage, select on sequence public.max_messages_id_seq to service_role;

-- Defence in depth if browser grants are ever added later. The sub-select
-- form lets Postgres initialise auth.uid() once per statement.
create policy max_conversations_owner_select on public.max_conversations
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy max_conversations_owner_insert on public.max_conversations
  for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy max_conversations_owner_update on public.max_conversations
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy max_conversations_owner_delete on public.max_conversations
  for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy max_messages_owner_select on public.max_messages
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy max_messages_owner_insert on public.max_messages
  for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy max_messages_owner_delete on public.max_messages
  for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy max_plan_items_owner_select on public.max_plan_items
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy max_plan_items_owner_insert on public.max_plan_items
  for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy max_plan_items_owner_update on public.max_plan_items
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy max_plan_items_owner_delete on public.max_plan_items
  for delete to authenticated
  using ((select auth.uid()) = user_id);
